# Laboratory Task 5

**Francis Rey C. Torillo**

**1. Perform Standard Imports**

In [13]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [14]:
!pip install torch torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable


In [15]:
import torch
import numpy as np
import sys

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

In [16]:
def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

In [17]:
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("arr:", arr)

arr: [3 4 2 4 4 1]


**4. Create a tensor "x" from the array above**

In [18]:
x = torch.from_numpy(arr)
print("x:", x)

x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


**5. Change the dtype of x from `int32` to `int64`**

In [19]:
x = x.type(torch.int64)
print("dtype:", x.dtype)

dtype: torch.int64


**6. Reshape `x` into a 3x2 tensor**

In [20]:
x = x.view(3, 2)
print("Reshaped x:\n", x)

Reshaped x:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


**7. Return the right-hand column of tensor `x`**

In [21]:
right_column = x[:, 1]
print("Right column:", right_column)

Right column: tensor([4, 4, 1])


**8. Without changing x, return a tensor of square values of `x`**

In [22]:
x_squared = x.pow(2)
# Alternatively: x_squared = x ** 2
print("Squared x:\n", x_squared)
print("Original x remains unchanged:\n", x)

Squared x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
Original x remains unchanged:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** 

In [23]:
torch.manual_seed(42)
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)
print("y:\n", y)
print("Number of elements in y:", y.numel())

y:
 tensor([[2, 2, 1],
        [4, 1, 0]])
Number of elements in y: 6


**10. Find the matrix product of `x` and `y`.**

In [24]:
matrix_product = torch.mm(x, y)
# Alternatively: matrix_product = x @ y
print("Matrix product (x @ y):\n", matrix_product)

Matrix product (x @ y):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
